name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get short SHA
      run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install cogs dotnet tool
      run: dotnet tool install --global --add-source https://ci.appveyor.com/nuget/cogs/ cogs

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install python dependencies
      run: pip install -r build/requirements.txt


    - name: Install other dependencies
      run: .\build\install-dependencies.ps1
      shell: pwsh

    - name: Run build-windows.bat
      run: .\build\build-windows.bat
      shell: cmd

    - name: Copy and rename outputs
      shell: pwsh
      run: |
        mkdir ddi-lifecycle
        xcopy ddi-lifecycle-all-outputs\xsd ddi-lifecycle\xsd /E /I
        xcopy ddi-lifecycle-all-outputs\json ddi-lifecycle\json /E /I
        xcopy ddi-lifecycle-all-outputs\owl ddi-lifecycle\rdf /E /I
        xcopy ddi-lifecycle-all-outputs\linkml ddi-lifecycle\rdf /E /I
        ren ddi-lifecycle ddi-lifecycle-${{env.SHORT_SHA}}
        ren ddi-lifecycle-all-outputs ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}
        7z a -tzip "ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}.zip" "ddi-lifecycle-all-outputs-${{ENV.SHORT_SHA}}\*"

    - name: Make all outputs artifact
      uses: actions/upload-artifact@v3
      with:
          name: ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}
          path: ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}.zip

    - name: Make package artifact
      uses: actions/upload-artifact@v3
      with:
        name: ddi-lifecycle-${{env.SHORT_SHA}}
        path: ddi-lifecycle-${{env.SHORT_SHA}}